"""change relation on Invoice to tg_user

Revision ID: 09d1b41a36a3
Revises: e14232d7f8cd
Create Date: 2024-07-25 11:32:22.693054

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "09d1b41a36a3"
down_revision = "e14232d7f8cd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invoice", sa.Column("tg_user_id", sa.BigInteger(), nullable=True))
    op.drop_constraint("fk_invoice_user_id_users", "invoice", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_invoice_tg_user_id_telegram_user"), "invoice", "telegram_user", ["tg_user_id"], ["id"]
    )
    op.drop_column("invoice", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invoice", sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f("fk_invoice_tg_user_id_telegram_user"), "invoice", type_="foreignkey")
    op.create_foreign_key("fk_invoice_user_id_users", "invoice", "users", ["user_id"], ["id"])
    op.drop_column("invoice", "tg_user_id")
    # ### end Alembic commands ###
