"""add Token and User models

Revision ID: 12c619b7bdc0
Revises:
Create Date: 2023-07-16 16:31:32.504249

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "12c619b7bdc0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_user_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["telegram_user_id"],
            ["telegram_user.id"],
            name=op.f("fk_user_telegram_user_id_telegram_user"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
    )
    op.create_table(
        "token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name=op.f("fk_token_user_id_user")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_token")),
    )
    op.drop_constraint("transcript_file_unique_id_key", "transcript", type_="unique")
    op.drop_constraint("transcript_sha256_hash_key", "transcript", type_="unique")
    op.create_unique_constraint(op.f("uq_transcript_file_unique_id"), "transcript", ["file_unique_id"])
    op.create_unique_constraint(op.f("uq_transcript_sha256_hash"), "transcript", ["sha256_hash"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_transcript_sha256_hash"), "transcript", type_="unique")
    op.drop_constraint(op.f("uq_transcript_file_unique_id"), "transcript", type_="unique")
    op.create_unique_constraint("transcript_sha256_hash_key", "transcript", ["sha256_hash"])
    op.create_unique_constraint("transcript_file_unique_id_key", "transcript", ["file_unique_id"])
    op.drop_table("token")
    op.drop_table("user")
    # ### end Alembic commands ###
