"""Make TelegramChat->Language optional

Revision ID: 188a84a328f8
Revises: cf3aacee6abc
Create Date: 2023-07-30 16:59:41.708419

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "188a84a328f8"
down_revision = "cf3aacee6abc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("telegram_chat", "language_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("telegram_chat", "language_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
