"""create m2m relationship to exclude languages

Revision ID: 24dfab84be35
Revises: 90bc624d3692
Create Date: 2025-07-19 04:16:45.706876

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "24dfab84be35"
down_revision = "90bc624d3692"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chats_to_excluded_languages_rel",
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("language_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"], ["telegram_chat.id"], name=op.f("fk_chats_to_excluded_languages_rel_chat_id_telegram_chat")
        ),
        sa.ForeignKeyConstraint(
            ["language_id"], ["language.id"], name=op.f("fk_chats_to_excluded_languages_rel_language_id_language")
        ),
        sa.PrimaryKeyConstraint("chat_id", "language_id", name=op.f("pk_chats_to_excluded_languages_rel")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chats_to_excluded_languages_rel")
    # ### end Alembic commands ###
