"""subscription logic

Revision ID: 43fa1a46e6c2
Revises: 72db6b646fe5
Create Date: 2023-08-04 12:54:30.713325

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "43fa1a46e6c2"
down_revision = "72db6b646fe5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscription", sa.Column("chat_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        op.f("fk_subscription_chat_id_telegram_chat"), "subscription", "telegram_chat", ["chat_id"], ["id"]
    )
    op.add_column("telegram_chat", sa.Column("title", sa.String(), nullable=True))
    op.add_column("telegram_chat", sa.Column("username", sa.String(), nullable=True))
    op.add_column("user", sa.Column("is_premium", sa.Boolean(), nullable=True))
    op.execute('UPDATE "user" SET is_premium = FALSE;')
    op.alter_column("user", "is_premium", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_premium")
    op.drop_column("telegram_chat", "username")
    op.drop_column("telegram_chat", "title")
    op.drop_constraint(op.f("fk_subscription_chat_id_telegram_chat"), "subscription", type_="foreignkey")
    op.drop_column("subscription", "chat_id")
    # ### end Alembic commands ###
