"""move tg_user and tg_chat relation to Summary

Revision ID: 4ffb2fa00b19
Revises: 673334ac8b3c
Create Date: 2024-08-06 17:34:32.395386

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4ffb2fa00b19"
down_revision = "673334ac8b3c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("summary", sa.Column("tg_user_id", sa.BigInteger(), nullable=True))
    op.add_column("summary", sa.Column("tg_chat_id", sa.BigInteger(), nullable=True))
    op.create_foreign_key(
        op.f("fk_summary_tg_chat_id_telegram_chat"), "summary", "telegram_chat", ["tg_chat_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_summary_tg_user_id_telegram_user"), "summary", "telegram_user", ["tg_user_id"], ["id"]
    )

    op.execute(
        """
        UPDATE summary
        SET tg_user_id = transcript.tg_user_id
        FROM transcript
        WHERE transcript_id = transcript.id
    """
    )

    op.drop_constraint("fk_transcript_tg_chat_id_telegram_chat", "transcript", type_="foreignkey")
    op.drop_constraint("fk_transcript_tg_user_id_telegram_user", "transcript", type_="foreignkey")
    op.drop_column("transcript", "tg_user_id")
    op.drop_column("transcript", "tg_chat_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transcript", sa.Column("tg_chat_id", sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column("transcript", sa.Column("tg_user_id", sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key(
        "fk_transcript_tg_user_id_telegram_user", "transcript", "telegram_user", ["tg_user_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_transcript_tg_chat_id_telegram_chat", "transcript", "telegram_chat", ["tg_chat_id"], ["id"]
    )
    op.drop_constraint(op.f("fk_summary_tg_user_id_telegram_user"), "summary", type_="foreignkey")
    op.drop_constraint(op.f("fk_summary_tg_chat_id_telegram_chat"), "summary", type_="foreignkey")
    op.drop_column("summary", "tg_chat_id")
    op.drop_column("summary", "tg_user_id")
    # ### end Alembic commands ###
