"""Make Transcript.duration Optional (support audio documents)

Revision ID: 50b6c003cdbb
Revises: aad719a7e141
Create Date: 2024-10-05 12:09:59.564897

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "50b6c003cdbb"
down_revision = "aad719a7e141"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("transcript", "duration", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("transcript", "duration", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
