"""add ondelete=CASCADE to summary/topic/translation

Revision ID: 5280326a34be
Revises: 69d04b0ec234
Create Date: 2023-08-10 07:26:05.114825

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "5280326a34be"
down_revision = "69d04b0ec234"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("topic_summary_id_fkey", "topic", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_topic_summary_id_summary"), "topic", "summary", ["summary_id"], ["id"], ondelete="CASCADE"
    )

    op.drop_constraint("translation_topic_id_fkey", "translation", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_translation_topic_id_topic"), "translation", "topic", ["topic_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_translation_topic_id_topic"), "translation", type_="foreignkey")
    op.create_foreign_key("fk_translation_topic_id_topic", "translation", "topic", ["topic_id"], ["id"])
    op.drop_constraint(op.f("fk_topic_summary_id_summary"), "topic", type_="foreignkey")
    op.create_foreign_key("fk_topic_summary_id_summary", "topic", "summary", ["summary_id"], ["id"])
    # ### end Alembic commands ###
