"""add discounted_price to Product

Revision ID: 5d5bcd24672e
Revises: 09d1b41a36a3
Create Date: 2024-08-06 13:17:59.868831

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5d5bcd24672e"
down_revision = "09d1b41a36a3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product", sa.Column("discounted_price", sa.Integer(), nullable=True))

    op.execute(
        """UPDATE product SET
            price = product_update.price,
            discounted_price = product.price
        FROM (VALUES
            ('MONTH', 500, 'XTR'),
            ('QUARTER', 1500, 'XTR'),
            ('YEAR', 6000, 'XTR')
        ) AS product_update(premium_period, price, currency)
        WHERE product.premium_period::text = product_update.premium_period
        AND product.currency = product_update.currency;
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "discounted_price")
    # ### end Alembic commands ###
