"""prepare Transcript model for text message processing

Revision ID: 5f7ac4e1f495
Revises: 90bc624d3692
Create Date: 2025-07-02 10:29:14.665705

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5f7ac4e1f495"
down_revision = "90bc624d3692"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("transcript", "file_id", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("transcript", "file_unique_id", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("transcript", "mime_type", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("transcript", "file_size", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("transcript", "file_size", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("transcript", "mime_type", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("transcript", "file_unique_id", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("transcript", "file_id", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
