"""add ondelete cascade on telegram_user -> user -> ...

Revision ID: 8e0d861d5ce0
Revises: a7a4bd897fda
Create Date: 2023-08-11 09:50:42.168071

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8e0d861d5ce0"
down_revision = "a7a4bd897fda"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("invoice", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("subscription", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("subscription", "chat_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint("fk_token_user_id_user", "token", type_="foreignkey")
    op.create_foreign_key(op.f("fk_token_user_id_user"), "token", "user", ["user_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint("fk_user_telegram_user_id_telegram_user", "user", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_user_telegram_user_id_telegram_user"),
        "user",
        "telegram_user",
        ["telegram_user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_user_telegram_user_id_telegram_user"), "user", type_="foreignkey")
    op.create_foreign_key(
        "fk_user_telegram_user_id_telegram_user", "user", "telegram_user", ["telegram_user_id"], ["id"]
    )
    op.drop_constraint(op.f("fk_token_user_id_user"), "token", type_="foreignkey")
    op.create_foreign_key("fk_token_user_id_user", "token", "user", ["user_id"], ["id"])
    op.alter_column("subscription", "chat_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("subscription", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("invoice", "user_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
