"""add finished_at columns to Summary, Transcript and TopicTranslation

Revision ID: a8ffea5dd099
Revises: 4ffb2fa00b19
Create Date: 2024-08-08 14:00:11.200727

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a8ffea5dd099"
down_revision = "4ffb2fa00b19"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("summary", sa.Column("finished_at", sa.DateTime(), nullable=True))
    op.add_column("transcript", sa.Column("finished_at", sa.DateTime(), nullable=True))
    op.add_column("translation", sa.Column("finished_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("translation", "finished_at")
    op.drop_column("transcript", "finished_at")
    op.drop_column("summary", "finished_at")
    # ### end Alembic commands ###
