"""Add total_seconds to Transcript model

Revision ID: aad719a7e141
Revises: 8186365a22ab
Create Date: 2024-09-07 10:14:33.233855

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "aad719a7e141"
down_revision = "8186365a22ab"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transcript", sa.Column("total_seconds", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transcript", "total_seconds")
    # ### end Alembic commands ###
