"""Add Translation model to DB

Revision ID: badaa335306f
Revises: e1ed85923fc2
Create Date: 2024-08-23 11:28:21.150349

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "badaa335306f"
down_revision = "e1ed85923fc2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "translation_i18n",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_text", sa.String(), nullable=False),
        sa.Column("target_text", sa.String(), nullable=False),
        sa.Column("target_lang_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["target_lang_id"], ["language.id"], name=op.f("fk_translation_i18n_target_lang_id_language")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_translation_i18n")),
    )
    op.alter_column("topic", "order", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("topic", "order", existing_type=sa.INTEGER(), nullable=True)
    op.drop_table("translation_i18n")
    # ### end Alembic commands ###
