"""Relate subscription to tg_user

Revision ID: d4bf60ad9041
Revises: a8ffea5dd099
Create Date: 2024-08-11 09:50:25.664706

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d4bf60ad9041"
down_revision = "a8ffea5dd099"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscription", sa.Column("tg_user_id", sa.BigInteger(), nullable=True))
    op.drop_constraint("fk_subscription_user_id_users", "subscription", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_subscription_tg_user_id_telegram_user"), "subscription", "telegram_user", ["tg_user_id"], ["id"]
    )
    op.drop_column("subscription", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscription", sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f("fk_subscription_tg_user_id_telegram_user"), "subscription", type_="foreignkey")
    op.create_foreign_key("fk_subscription_user_id_users", "subscription", "users", ["user_id"], ["id"])
    op.drop_column("subscription", "tg_user_id")
    # ### end Alembic commands ###
