"""rename user table (interally used by psql)

Revision ID: e619dc0a2844
Revises: 8e0d861d5ce0
Create Date: 2023-08-11 10:04:03.801517

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e619dc0a2844"
down_revision = "8e0d861d5ce0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("user", "users")
    op.alter_column("invoice", "chat_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint("fk_invoice_user_id_user", "invoice", type_="foreignkey")
    op.create_foreign_key(op.f("fk_invoice_user_id_users"), "invoice", "users", ["user_id"], ["id"])
    op.drop_constraint("fk_subscription_user_id_user", "subscription", type_="foreignkey")
    op.create_foreign_key(op.f("fk_subscription_user_id_users"), "subscription", "users", ["user_id"], ["id"])
    op.drop_constraint("fk_token_user_id_user", "token", type_="foreignkey")
    op.create_foreign_key(op.f("fk_token_user_id_users"), "token", "users", ["user_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("users", "user")
    op.drop_constraint(op.f("fk_token_user_id_users"), "token", type_="foreignkey")
    op.create_foreign_key("fk_token_user_id_user", "token", "user", ["user_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint(op.f("fk_subscription_user_id_users"), "subscription", type_="foreignkey")
    op.create_foreign_key("fk_subscription_user_id_user", "subscription", "user", ["user_id"], ["id"])
    op.drop_constraint(op.f("fk_invoice_user_id_users"), "invoice", type_="foreignkey")
    op.create_foreign_key("fk_invoice_user_id_user", "invoice", "user", ["user_id"], ["id"])
    op.alter_column("invoice", "chat_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
