"""Add referral token

Revision ID: f2e59c721760
Revises: 188a84a328f8
Create Date: 2023-08-03 17:50:06.028113

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f2e59c721760"
down_revision = "188a84a328f8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("referral_token", sa.String(), nullable=True, unique=True))
    # need pgcrypto extension for this to work
    # https://dba.stackexchange.com/a/262582
    # https://www.postgresql.org/docs/15/functions-binarystring.html
    op.execute(r"""UPDATE "user" SET referral_token = (substr(encode(gen_random_bytes(4), 'base64'), 1, 6));""")
    op.alter_column("user", "referral_token", existing_type=sa.String(), nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "referral_token")
    # ### end Alembic commands ###
